run: naming

naming:
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_01_p.sv > pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_02_f.sv >> pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_03_p.sv >> pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_04_f.sv >> pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_05_p.sv >> pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_06_f.sv >> pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_07_p.sv >> pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_08_f.sv >> pyslint.log

	cat pyslint.log

