run: naming

naming:
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_01.sv > pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_02.sv >> pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_03.sv >> pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_04.sv >> pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_05.sv >> pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_06.sv >> pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_07.sv >> pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_08.sv >> pyslint.log

	cat pyslint.log

