run: naming

naming:
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_01_p.sv > pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_02_f.sv >> pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_03_p.sv >> pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_04_f.sv >> pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_05_p.sv >> pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_06_f.sv >> pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_07_p.sv >> pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_08_f.sv >> pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_09_p.sv >> pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_10_f.sv >> pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_11_f.sv >> pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_12_f.sv >> pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_13_f.sv >> pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_14_p.sv >> pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_15_f.sv >> pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_16_f.sv >> pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_17_f.sv >> pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_18_f.sv >> pyslint.log
	python3 ../py_src/pyslint.py -t ../sv_tests/test_sv_naming_19_f.sv >> pyslint.log

	cat pyslint.log

